import React, { useCallback, useEffect, useState } from "react";
import { View, Text, StyleSheet, Pressable, ActivityIndicator, Modal, FlatList } from "react-native";
import { Image } from "expo-image";
import { Video, ResizeMode } from "expo-av";
import { Feather } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { getGroupMedia, type ChatMessage } from "../lib/db_logic";
import Colors from "@/constants/colors";
const C=Colors.light;
export default function GroupMediaScreen(){
 const {chatId}=useLocalSearchParams<{chatId:string}>(); const insets=useSafeAreaInsets(); const [items,setItems]=useState<ChatMessage[]>([]); const [loading,setLoading]=useState(true); const [viewer,setViewer]=useState<ChatMessage|null>(null);
 const load=useCallback(async()=>{if(!chatId)return;try{setItems(await getGroupMedia(chatId));}finally{setLoading(false)}},[chatId]); useEffect(()=>{load()},[load]);
 return <View style={styles.root}><View style={[styles.header,{paddingTop:insets.top+8}]}><Pressable style={styles.back} onPress={()=>router.back()}><Feather name="chevron-right" size={24} color="#FFF"/></Pressable><Text style={styles.title}>وسائط المجموعة</Text><View style={{width:38}}/></View>{loading?<View style={styles.center}><ActivityIndicator size="large" color={C.accent}/></View>:items.length===0?<View style={styles.center}><Feather name="image" size={42} color={C.textMuted}/><Text style={styles.empty}>لا توجد صور أو فيديوهات</Text></View>:<FlatList data={items} numColumns={3} keyExtractor={m=>m.id} contentContainerStyle={{padding:3,paddingBottom:insets.bottom+15}} renderItem={({item})=><Pressable style={styles.tile} onPress={()=>setViewer(item)}>{item.type==="video"?<><Video source={{uri:item.mediaUrl}} style={styles.media} resizeMode={ResizeMode.COVER} shouldPlay={false} useNativeControls={false}/><View style={styles.play}><Feather name="play" size={18} color="#FFF"/></View></>:<Image source={{uri:item.mediaUrl}} style={styles.media} contentFit="cover"/>}</Pressable>}/>}<Modal visible={!!viewer} transparent animationType="fade" onRequestClose={()=>setViewer(null)}><View style={styles.viewer}><Pressable style={styles.close} onPress={()=>setViewer(null)}><Feather name="x" size={28} color="#FFF"/></Pressable>{viewer?.type==="video"?<Video source={{uri:viewer.mediaUrl}} style={styles.full} resizeMode={ResizeMode.CONTAIN} shouldPlay useNativeControls/>:<Image source={{uri:viewer?.mediaUrl}} style={styles.full} contentFit="contain"/>}</View></Modal></View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:C.background},header:{backgroundColor:"#0D1B3E",flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:14,paddingBottom:14},back:{width:38,height:38,borderRadius:10,backgroundColor:"rgba(255,255,255,.12)",alignItems:"center",justifyContent:"center"},title:{color:"#FFF",fontFamily:"Cairo_700Bold",fontSize:17},center:{flex:1,alignItems:"center",justifyContent:"center",gap:10},empty:{color:C.textMuted,fontFamily:"Cairo_400Regular"},tile:{width:"33.333%",aspectRatio:1,padding:2},media:{width:"100%",height:"100%"},play:{position:"absolute",left:"50%",top:"50%",marginLeft:-18,marginTop:-18,width:36,height:36,borderRadius:18,backgroundColor:"rgba(0,0,0,.6)",alignItems:"center",justifyContent:"center"},viewer:{flex:1,backgroundColor:"#000",alignItems:"center",justifyContent:"center"},full:{width:"100%",height:"100%"},close:{position:"absolute",zIndex:10,top:35,right:18,width:42,height:42,borderRadius:21,backgroundColor:"rgba(0,0,0,.55)",alignItems:"center",justifyContent:"center"}});
